// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEcvcrdD-7gwWZHiYfQxRh9ICwFx8QcQ8',
    appId: '1:247543660705:web:6754e235c5812b2935f0e0',
    messagingSenderId: '247543660705',
    projectId: 'chatapp-c01f2',
    authDomain: 'chatapp-c01f2.firebaseapp.com',
    storageBucket: 'chatapp-c01f2.firebasestorage.app',
    measurementId: 'G-3NEW89BKNW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRLdX3-1qvdwPVYitkCb2CAU8poo6wLYM',
    appId: '1:247543660705:android:4c404c071d6cfee235f0e0',
    messagingSenderId: '247543660705',
    projectId: 'chatapp-c01f2',
    storageBucket: 'chatapp-c01f2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMBAgOCjbNowsx3iv56nijJ02IKFcT9Ww',
    appId: '1:247543660705:ios:70b94ef74084635a35f0e0',
    messagingSenderId: '247543660705',
    projectId: 'chatapp-c01f2',
    storageBucket: 'chatapp-c01f2.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMBAgOCjbNowsx3iv56nijJ02IKFcT9Ww',
    appId: '1:247543660705:ios:70b94ef74084635a35f0e0',
    messagingSenderId: '247543660705',
    projectId: 'chatapp-c01f2',
    storageBucket: 'chatapp-c01f2.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEcvcrdD-7gwWZHiYfQxRh9ICwFx8QcQ8',
    appId: '1:247543660705:web:8e67729dc571b0ad35f0e0',
    messagingSenderId: '247543660705',
    projectId: 'chatapp-c01f2',
    authDomain: 'chatapp-c01f2.firebaseapp.com',
    storageBucket: 'chatapp-c01f2.firebasestorage.app',
    measurementId: 'G-FWTYT0NWE7',
  );
}
